name: Docker Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Static Code Linting with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t victorm44/mysql:${{ github.sha }} .

  manual-approval:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Wait for manual approval
        id: approval
        uses: "actions/github-script@v4"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'master'
            });

            const pullRequest = response.data.find(pr => pr.head.sha === context.sha);

            if (!pullRequest) {
              core.setFailed("Pull request not found.");
              return;
            }

            console.log(`PR#${pullRequest.number} is ready for approval.`);
            core.setOutput("pull_request_number", pullRequest.number);
      
      - name: Comment on PR
        if: steps.approval.outputs.pull_request_number
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequestNumber = workflow.outputs.pull_request_number;
            const comment = "La construcción ha finalizado. Por favor, aprueba manualmente para proceder con la publicación.";

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              body: comment
            });
