name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --region ${{ env.AWS_REGION }}       
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ${{ env.AWS_REGION }}

    - name: Build docker image
      run: |
        docker build -t backend-app .

    - name: Tag image
      run: |
        docker tag backend-app:latest ${{ secrets.ECR_REPOSITORY_URL }}/backend-app:latest

    - name: Push image
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URL }}/backend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --region ${{ env.AWS_REGION }}       
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ${{ env.AWS_REGION }}

    - name: Pull image
      run: |
        docker pull ${{ secrets.ECR_REPOSITORY_URL }}/backend-app:latest
