name: Docker Publish and Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      # ... pasos de prueba y linting ...

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # ... pasos de construcción y publicación de Docker ...

  manual-approval:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      # ... pasos de aprobación manual ...

  static-analysis:
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Instala las herramientas necesarias para el análisis estático aquí

      - name: Run static code analysis
        run: |
          # Ejecuta la herramienta de análisis estático aquí

